### ISSUE TITLE
lower fps

### ISSUE THREAD

**Issue by farhantandia** [Tqualizer/Directional-object-tracking-with-TFLite-and-Edge-TPU#2]
hi, I try your code and it works smoothly, but I only got 6 fps instead of 12 fps, how you can get that fps ? or do I missed something? thanks.
I used DirectionTracker.py with your video sample.
` python3 TFLite_DirectionTracker.py --modeldir=Sample_TFLite_model --edgetpu --resolution=640x480 --video=Examples/bustling.mp4
`

**Comment by Tqualizer** [comment]
It's been a while since I properly tested the performance but from what I can remember the FPS was lower with more objects on the screen like in the recorded sample video. When tracking up to 5 objects live from the camera I still comfortably got >10 FPS
