### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by kiraans** [Tqualizer/Directional-object-tracking-with-TFLite-and-Edge-TPU#3]
```
File "TFLite_DirectionTracker.py", line 203, in <module>
    ymin = int(max(1,(boxes[i][0] * imH)))
IndexError: invalid index to scalar variable.
```
I am getting this error while trying to run the TFLite_DirectionTracker.py for a custom video.

**Comment by Tqualizer** [comment]
Thanks for raising this. Just to confirm was there no errors running the script against the original sample video included in the repo and you are running against your own custom video?

**Comment by kiraans** [comment]
Thank you for the reply. I actually trained the model using a custom dataset on TensorFlow 2 and exported the Tflite model. But it seems like, there is some issue with the model itself. So I am trying to train the model using TensorFlow 1 version and will check if the problem still persist.

**Comment by kiraans** [comment]
I could run the code using the pre-trained tflite model. But there is still some compatibility issue with the TensorFlow 2 custom data model. Hopefully, there will be an update on this.
